IMAGE_OBJECT_DETECTION_MODE = '<OD>'
IMAGE_CAPTIONING_MODE = '<MORE_DETAILED_CAPTION>'

FLORENCE_OBJECT_DETECTION_TASK = '<OD>'



IMAGE_OPEN_VOCABULARY_DETECTION_MODE = "open vocabulary detection"
IMAGE_CAPTION_GROUNDING_MODE = "caption + phrase grounding"

IMAGE_INFERENCE_MODES = [
    IMAGE_OPEN_VOCABULARY_DETECTION_MODE,
    IMAGE_CAPTION_GROUNDING_MODE
]
